// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dvdrental

type NewAddress struct {
	Address    string  `json:"address"`
	Address2   *string `json:"address2"`
	District   string  `json:"district"`
	PostalCode *string `json:"postalCode"`
	Phone      *string `json:"phone"`
}

type NewStaff struct {
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Email     string  `json:"email"`
	Active    *bool   `json:"active"`
	Username  string  `json:"username"`
	Password  string  `json:"password"`
}
